import datasets

dataset_features = datasets.Features({
    "usajobsControlNumber": datasets.Value("string"),
    "wage_min": datasets.Value("string"),
    "wage_max": datasets.Value("string"),
    "wage_freq": datasets.Value("string"),
    "title_code": datasets.Value("string"),
    "title_score": datasets.Value("float32"),
    "title_value": datasets.Value("float32"),
    "title_features": datasets.Value("string"),
    "flesch_kincaid": datasets.Value("float32"),
    "CitizenshipReq": datasets.Value("bool"),
    "GovContract": datasets.Value("bool"),
    "VisaExclude": datasets.Value("bool"),
    "VisaInclude": datasets.Value("bool"),
    "WorkAuthReq": datasets.Value("bool"),
    "driverslicense": datasets.Value("bool"),
    "ind_contractor": datasets.Value("bool"),
    "proflicenses": datasets.Value("bool"),
    "wfh": datasets.Value("bool"),
    "yesunion": datasets.Value("bool"),
    "tasks": datasets.Value("string"),
    "skills": datasets.Value("string"),
    "concepts": datasets.Value("string"), 
    "ai_codes": datasets.Value("string"),
    "ai_matches": datasets.Value("int8"),
    "ai_score": datasets.Value("float32"),
    "ai_selection_score": datasets.Value("string"),
    "ai_match_score": datasets.Value("string"),
    "ai_score_v2": datasets.Value("float32"),
    "ai_strict_score": datasets.Value("float32"),
    "ai_lenient_score": datasets.Value("float32")
})

pandas_dtypes = {
    "usajobsControlNumber": "string",
    "wage_min": "string",
    "title_code": "string",
    "title_features": "string",
    "tasks": "string",
    "skills": "string",
    "concepts": "string",
    "ai_codes": "string",
    "ai_selection_score": "string",
    "ai_match_score": "string",
    "wage_freq": "string",
    "wage_max": "string",
    "wage_max": "string", 
    "title_score": "Float32",
    "title_value": "Float32", 
    "flesch_kincaid": "Float32",
    "ai_score": "Float32",
    "ai_score_v2": "Float32",
    "ai_strict_score": "Float32",
    "ai_lenient_score": "Float32",
    "ai_matches": "Int8",
    "CitizenshipReq": "boolean",
    "GovContract": "boolean",
    "VisaExclude": "boolean",
    "VisaInclude": "boolean",
    "WorkAuthReq": "boolean",
    "driverslicense": "boolean",
    "ind_contractor": "boolean",
    "proflicenses": "boolean",
    "wfh": "boolean",
    "yesunion": "boolean"
}